package simulation.enfa

import de.tu_dortmund.cs.ls14.cls.interpreter.combinator
import de.tu_dortmund.cs.ls14.cls.types._
import de.tu_dortmund.cs.ls14.cls.types.syntax._
import simulation.AutomatonCombinators

/**
  * In diesem Repository wird das Symbol für Leerzeichen als 'space bezeichnet.
  */
trait GameRepository extends AutomatonCombinators {

  private val id: Unit => Unit = identity

  // Gamma 1, Section 4.3.2
  @combinator object RunNfa extends Run[Unit]('start)

  @combinator object EpsS_W1 extends EpsilonTransition('start, 'w1)(id)
  @combinator object W1_F extends Transition('w1, 'F(_), 'wF)
  @combinator object WF_i extends Transition('wF, 'i(_), 'wFi)
  @combinator object WFi_r extends Transition('wFi, 'r(_), 'wFir)
  @combinator object WFir_e extends Transition('wFir, 'e(_), 'wFire)
  @combinator object FinFire extends Fin('wFire)(())

  @combinator object EpsS_W2 extends EpsilonTransition('start, 'w2)(id)
  @combinator object W2_I extends Transition('w1, 'I(_), 'wI)
  @combinator object WI_c extends Transition('wF, 'c(_), 'wIc)
  @combinator object WIc_e extends Transition('wFi, 'e(_), 'wIce)
  @combinator object FinIce extends Fin('wIce)(())

  // Gamma 2
  @combinator object S_A extends Transition('start, 'A(_), 'start)
  @combinator object S_B extends Transition('start, 'B(_), 'start)
  @combinator object S_C extends Transition('start, 'C(_), 'start)
  @combinator object S_D extends Transition('start, 'D(_), 'start)
  @combinator object S_E extends Transition('start, 'E(_), 'start)
  @combinator object S_F extends Transition('start, 'F(_), 'start)
  @combinator object S_G extends Transition('start, 'G(_), 'start)
  @combinator object S_H extends Transition('start, 'H(_), 'start)
  @combinator object S_I extends Transition('start, 'I(_), 'start)
  @combinator object S_J extends Transition('start, 'J(_), 'start)
  @combinator object S_K extends Transition('start, 'K(_), 'start)
  @combinator object S_L extends Transition('start, 'L(_), 'start)
  @combinator object S_M extends Transition('start, 'M(_), 'start)
  @combinator object S_N extends Transition('start, 'N(_), 'start)
  @combinator object S_O extends Transition('start, 'O(_), 'start)
  @combinator object S_P extends Transition('start, 'P(_), 'start)
  @combinator object S_Q extends Transition('start, 'Q(_), 'start)
  @combinator object S_R extends Transition('start, 'R(_), 'start)
  @combinator object S_S extends Transition('start, 'S(_), 'start)
  @combinator object S_T extends Transition('start, 'T(_), 'start)
  @combinator object S_U extends Transition('start, 'U(_), 'start)
  @combinator object S_V extends Transition('start, 'V(_), 'start)
  @combinator object S_W extends Transition('start, 'W(_), 'start)
  @combinator object S_X extends Transition('start, 'X(_), 'start)
  @combinator object S_Y extends Transition('start, 'Y(_), 'start)
  @combinator object S_Z extends Transition('start, 'Z(_), 'start)

  @combinator object S_a extends Transition('start, 'a(_), 'start)
  @combinator object S_b extends Transition('start, 'b(_), 'start)
  @combinator object S_c extends Transition('start, 'c(_), 'start)
  @combinator object S_d extends Transition('start, 'd(_), 'start)
  @combinator object S_e extends Transition('start, 'e(_), 'start)
  @combinator object S_f extends Transition('start, 'f(_), 'start)
  @combinator object S_g extends Transition('start, 'g(_), 'start)
  @combinator object S_h extends Transition('start, 'h(_), 'start)
  @combinator object S_i extends Transition('start, 'i(_), 'start)
  @combinator object S_j extends Transition('start, 'j(_), 'start)
  @combinator object S_k extends Transition('start, 'k(_), 'start)
  @combinator object S_l extends Transition('start, 'l(_), 'start)
  @combinator object S_m extends Transition('start, 'm(_), 'start)
  @combinator object S_n extends Transition('start, 'n(_), 'start)
  @combinator object S_o extends Transition('start, 'o(_), 'start)
  @combinator object S_p extends Transition('start, 'p(_), 'start)
  @combinator object S_q extends Transition('start, 'q(_), 'start)
  @combinator object S_r extends Transition('start, 'r(_), 'start)
  @combinator object S_s extends Transition('start, 's(_), 'start)
  @combinator object S_t extends Transition('start, 't(_), 'start)
  @combinator object S_u extends Transition('start, 'u(_), 'start)
  @combinator object S_v extends Transition('start, 'v(_), 'start)
  @combinator object S_w extends Transition('start, 'w(_), 'start)
  @combinator object S_x extends Transition('start, 'x(_), 'start)
  @combinator object S_y extends Transition('start, 'y(_), 'start)
  @combinator object S_z extends Transition('start, 'z(_), 'start)

  @combinator object S_Space extends Transition('start, 'space(_), 'start)

  // Gamma 3
  @combinator object WFire_A extends Transition('wFire, 'A(_), 'wFire)
  @combinator object WFire_B extends Transition('wFire, 'B(_), 'wFire)
  @combinator object WFire_C extends Transition('wFire, 'C(_), 'wFire)
  @combinator object WFire_D extends Transition('wFire, 'D(_), 'wFire)
  @combinator object WFire_E extends Transition('wFire, 'E(_), 'wFire)
  @combinator object WFire_F extends Transition('wFire, 'F(_), 'wFire)
  @combinator object WFire_G extends Transition('wFire, 'G(_), 'wFire)
  @combinator object WFire_H extends Transition('wFire, 'H(_), 'wFire)
  @combinator object WFire_I extends Transition('wFire, 'I(_), 'wFire)
  @combinator object WFire_J extends Transition('wFire, 'J(_), 'wFire)
  @combinator object WFire_K extends Transition('wFire, 'K(_), 'wFire)
  @combinator object WFire_L extends Transition('wFire, 'L(_), 'wFire)
  @combinator object WFire_M extends Transition('wFire, 'M(_), 'wFire)
  @combinator object WFire_N extends Transition('wFire, 'N(_), 'wFire)
  @combinator object WFire_O extends Transition('wFire, 'O(_), 'wFire)
  @combinator object WFire_P extends Transition('wFire, 'P(_), 'wFire)
  @combinator object WFire_Q extends Transition('wFire, 'Q(_), 'wFire)
  @combinator object WFire_R extends Transition('wFire, 'R(_), 'wFire)
  @combinator object WFire_S extends Transition('wFire, 'S(_), 'wFire)
  @combinator object WFire_T extends Transition('wFire, 'T(_), 'wFire)
  @combinator object WFire_U extends Transition('wFire, 'U(_), 'wFire)
  @combinator object WFire_V extends Transition('wFire, 'V(_), 'wFire)
  @combinator object WFire_W extends Transition('wFire, 'W(_), 'wFire)
  @combinator object WFire_X extends Transition('wFire, 'X(_), 'wFire)
  @combinator object WFire_Y extends Transition('wFire, 'Y(_), 'wFire)
  @combinator object WFire_Z extends Transition('wFire, 'Z(_), 'wFire)

  @combinator object WFire_a extends Transition('wFire, 'a(_), 'wFire)
  @combinator object WFire_b extends Transition('wFire, 'b(_), 'wFire)
  @combinator object WFire_c extends Transition('wFire, 'c(_), 'wFire)
  @combinator object WFire_d extends Transition('wFire, 'd(_), 'wFire)
  @combinator object WFire_e extends Transition('wFire, 'e(_), 'wFire)
  @combinator object WFire_f extends Transition('wFire, 'f(_), 'wFire)
  @combinator object WFire_g extends Transition('wFire, 'g(_), 'wFire)
  @combinator object WFire_h extends Transition('wFire, 'h(_), 'wFire)
  @combinator object WFire_i extends Transition('wFire, 'i(_), 'wFire)
  @combinator object WFire_j extends Transition('wFire, 'j(_), 'wFire)
  @combinator object WFire_k extends Transition('wFire, 'k(_), 'wFire)
  @combinator object WFire_l extends Transition('wFire, 'l(_), 'wFire)
  @combinator object WFire_m extends Transition('wFire, 'm(_), 'wFire)
  @combinator object WFire_n extends Transition('wFire, 'n(_), 'wFire)
  @combinator object WFire_o extends Transition('wFire, 'o(_), 'wFire)
  @combinator object WFire_p extends Transition('wFire, 'p(_), 'wFire)
  @combinator object WFire_q extends Transition('wFire, 'q(_), 'wFire)
  @combinator object WFire_r extends Transition('wFire, 'r(_), 'wFire)
  @combinator object WFire_s extends Transition('wFire, 's(_), 'wFire)
  @combinator object WFire_t extends Transition('wFire, 't(_), 'wFire)
  @combinator object WFire_u extends Transition('wFire, 'u(_), 'wFire)
  @combinator object WFire_v extends Transition('wFire, 'v(_), 'wFire)
  @combinator object WFire_w extends Transition('wFire, 'w(_), 'wFire)
  @combinator object WFire_x extends Transition('wFire, 'x(_), 'wFire)
  @combinator object WFire_y extends Transition('wFire, 'y(_), 'wFire)
  @combinator object WFire_z extends Transition('wFire, 'z(_), 'wFire)

  @combinator object WFire_Space extends Transition('wFire, 'space(_), 'wFire)

  @combinator object WIce_A extends Transition('wIce, 'A(_), 'wIce)
  @combinator object WIce_B extends Transition('wIce, 'B(_), 'wIce)
  @combinator object WIce_C extends Transition('wIce, 'C(_), 'wIce)
  @combinator object WIce_D extends Transition('wIce, 'D(_), 'wIce)
  @combinator object WIce_E extends Transition('wIce, 'E(_), 'wIce)
  @combinator object WIce_F extends Transition('wIce, 'F(_), 'wIce)
  @combinator object WIce_G extends Transition('wIce, 'G(_), 'wIce)
  @combinator object WIce_H extends Transition('wIce, 'H(_), 'wIce)
  @combinator object WIce_I extends Transition('wIce, 'I(_), 'wIce)
  @combinator object WIce_J extends Transition('wIce, 'J(_), 'wIce)
  @combinator object WIce_K extends Transition('wIce, 'K(_), 'wIce)
  @combinator object WIce_L extends Transition('wIce, 'L(_), 'wIce)
  @combinator object WIce_M extends Transition('wIce, 'M(_), 'wIce)
  @combinator object WIce_N extends Transition('wIce, 'N(_), 'wIce)
  @combinator object WIce_O extends Transition('wIce, 'O(_), 'wIce)
  @combinator object WIce_P extends Transition('wIce, 'P(_), 'wIce)
  @combinator object WIce_Q extends Transition('wIce, 'Q(_), 'wIce)
  @combinator object WIce_R extends Transition('wIce, 'R(_), 'wIce)
  @combinator object WIce_S extends Transition('wIce, 'S(_), 'wIce)
  @combinator object WIce_T extends Transition('wIce, 'T(_), 'wIce)
  @combinator object WIce_U extends Transition('wIce, 'U(_), 'wIce)
  @combinator object WIce_V extends Transition('wIce, 'V(_), 'wIce)
  @combinator object WIce_W extends Transition('wIce, 'W(_), 'wIce)
  @combinator object WIce_X extends Transition('wIce, 'X(_), 'wIce)
  @combinator object WIce_Y extends Transition('wIce, 'Y(_), 'wIce)
  @combinator object WIce_Z extends Transition('wIce, 'Z(_), 'wIce)

  @combinator object WIce_a extends Transition('wIce, 'a(_), 'wIce)
  @combinator object WIce_b extends Transition('wIce, 'b(_), 'wIce)
  @combinator object WIce_c extends Transition('wIce, 'c(_), 'wIce)
  @combinator object WIce_d extends Transition('wIce, 'd(_), 'wIce)
  @combinator object WIce_e extends Transition('wIce, 'e(_), 'wIce)
  @combinator object WIce_f extends Transition('wIce, 'f(_), 'wIce)
  @combinator object WIce_g extends Transition('wIce, 'g(_), 'wIce)
  @combinator object WIce_h extends Transition('wIce, 'h(_), 'wIce)
  @combinator object WIce_i extends Transition('wIce, 'i(_), 'wIce)
  @combinator object WIce_j extends Transition('wIce, 'j(_), 'wIce)
  @combinator object WIce_k extends Transition('wIce, 'k(_), 'wIce)
  @combinator object WIce_l extends Transition('wIce, 'l(_), 'wIce)
  @combinator object WIce_m extends Transition('wIce, 'm(_), 'wIce)
  @combinator object WIce_n extends Transition('wIce, 'n(_), 'wIce)
  @combinator object WIce_o extends Transition('wIce, 'o(_), 'wIce)
  @combinator object WIce_p extends Transition('wIce, 'p(_), 'wIce)
  @combinator object WIce_q extends Transition('wIce, 'q(_), 'wIce)
  @combinator object WIce_r extends Transition('wIce, 'r(_), 'wIce)
  @combinator object WIce_s extends Transition('wIce, 's(_), 'wIce)
  @combinator object WIce_t extends Transition('wIce, 't(_), 'wIce)
  @combinator object WIce_u extends Transition('wIce, 'u(_), 'wIce)
  @combinator object WIce_v extends Transition('wIce, 'v(_), 'wIce)
  @combinator object WIce_w extends Transition('wIce, 'w(_), 'wIce)
  @combinator object WIce_x extends Transition('wIce, 'x(_), 'wIce)
  @combinator object WIce_y extends Transition('wIce, 'y(_), 'wIce)
  @combinator object WIce_z extends Transition('wIce, 'z(_), 'wIce)

  @combinator object WIce_Space extends Transition('wIce, 'space(_), 'wIce)

}
